<?php $qis = $this->qis;
	$categories = $this->categories;?>
<div class="row content-heading title">
	<div class="col-xs-11 col-xs-offset-1">
		<h2>Liste des dossiers de Question Indépendante : </h2>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<button class="center btn btn-primary btn-lg" data-toggle="modal" data-target="#ajoutQi">
			Ajouter un dossier de QI
		</button>

		<br/><br/>

		<?php if ($qis): ?>
			<div class="table-responsive">
				<table class="center table table-striped table-hover">
					<thead>
						<tr>
							<th class="center">Nom</th>
							<th class="center">Catégorie</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						<?php foreach ($qis as $qi): ?>
							<tr>
								<td><a href="/qi/questionqi?idQi=<?= $qi['id']; ?>"><?= $qi['nom']; ?></a></td>
								<td><?= $qi['idCategorie']; ?></td>
								<td><a href="/qi/supprimer?id=<?= $qi['id']; ?>" onClick="return confirm('Etes vous sur de vouloir supprimer ce dossier de QI ?');" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"> Supprimer</span></a></td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		<?php else: ?>
			<p class="center">Il n'y a aucun Dossier de QI pour le moment.</p>
		<?php endif; ?>
	</div>
</div>

<!-- MODAL -->
<div class="modal fade" id="ajoutQi" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Ajouter un dossier de QI</h4>
			</div>

			<form method="POST" action="/qi/ajout">
				<div class="modal-body">
					<input type="text" class="form-control" placeholder="Nom du dossier de QI" name="name"><br/>


					<label>Catégorie</label>
				   	<select class="form-control" name="idCategorie">
						<?php foreach ($categories as $categorie):?>
							<option value="<?= $categorie['id'] ;?>"><?= $categorie['nom'] ;?></option>
						<?php endforeach; ?>
					</select>

				</div>


				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
					<input type="submit" class="btn btn-success" value="Enregistrer" />
				</div>
			</form>
		</div>
	</div>
</div>
