<?php
	$reponses = $this->reponsesqi;
	$typeQuestion = $this->typeQuestion;
?>
<?php if($typeQuestion['idTypeQuestion'] == 2): ?>
<div class="row content-heading title">
	<div class="col-xs-11 col-xs-offset-1">
		<h2>Liste des réponses :</h2>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<button class="center btn btn-primary btn-lg" data-toggle="modal" data-target="#ajoutRep">
			Ajouter des réponses
		</button>

		<br/><br/>

		<?php if($reponses): ?>
			<div class="table-responsive">
				<table class="center table table-striped table-hover">
					<thead>
						<tr>
							<th>Intitulé</th>
							<th>Nombre de point</th>
							<th>Effet sur point</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						<?php foreach($reponses as $reponse): ?>
							<tr>
								<td><?= $reponse['intitule']; ?></td>
								<td><?= $reponse['nbPoint']; ?></td>
								<td><?= $reponse['effetSurPoint']; ?></td>
								<td>
									<a href="/qi/supprimerreponse?idReponse=<?= $reponse['id']; ?>&idQi=<?= $_GET['idQi'];?>&idQuestion=<?= $_GET['idQuestion'];?>" onClick="return confirm('Etes vous sur de vouloir supprimer cette réponse ?');" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"> Supprimer</span></a>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		<?php else: ?>
			<p class="center">Il n'y a aucune réponse pour le moment.</p>
		<?php endif; ?>
	</div>
</div>

<!-- MODAL -->
<div class="modal fade" id="ajoutRep" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Ajouter des réponses</h4>
			</div>

			<form method="POST" action="/dcp/ajoutreponse">
				<div class="modal-body">
					<input type="hidden" name="idQuestion[1]" value="<?= $_GET['idQuestion']; ?>" />
					<input type="hidden" name="idQi[1]" value="<?= $_GET['idQi']; ?>" />
					Réponse 1 : <br />
					<input type="text" class="form-control input_reponse" placeholder="Votre réponse" name="rep[1]"><br/>
					<label>Valeur en point(s) :</label>
			   		<select name="point[1]" class="form-control">
			   			<?php for ($i = 1; $i <= 20; $i++): ?>
					   		<option value="<?= $i; ?>"><?= $i; ?></option>
					   	<?php endfor; ?>
			   		</select><br />

			   		<select name="action[1]" class="form-control">
			   			<option value="1">Positif</option>
			   			<option value="2">Négatif</option>
			   			<option value="3">Neutre</option>
			   		</select>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-info btn-add">Ajouter plus de réponse</button>
					<button type="submit" class="btn btn-success">Enregistrer</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.btn-add').on('click', function(e){
			nombre = $('.input_reponse').length;
			if (nombre >= 12){
				alert('Vous ne pouvez plus ajouter de réponse.');
			} else {
				$('.modal-body').append('<br /><br />Réponse '+(nombre+1)+
					'<input type="text" class="form-control input_reponse" placeholder="Votre réponse" name="rep['+(nombre+1)+']" /><br/>'+
					'<label>Valeur en point(s) :</label>'+
			   		'<select name="point['+(nombre+1)+']" class="form-control">'+
			   			'<option value="1">1</option>'+
			   			'<option value="2">2</option>'+
			   			'<option value="3">3</option>'+
			   			'<option value="4">4</option>'+
			   			'<option value="5">5</option>'+
			   			'<option value="6">6</option>'+
			   			'<option value="7">7</option>'+
			   			'<option value="8">8</option>'+
			   			'<option value="9">9</option>'+
			   			'<option value="10">10</option>'+
			   		'</select><br />'+

			   		'<select name="action['+(nombre+1)+']" class="form-control">'+
			   			'<option value="1">Positif</option>'+
			   			'<option value="2">Négatif</option>'+
			   			'<option value="3">Neutre</option>'+
			   		'</select>'
				);
			}
		});
	});
</script>

<?php else: //si c'est pas un choix multiple  ?>

<div class="row content-heading title">
	<div class="col-xs-11 col-xs-offset-1">
		<h2>Liste des réponses valides :</h2>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<button class="center btn btn-primary btn-lg" data-toggle="modal" data-target="#ajoutRep">
			Ajouter des réponses
		</button>

		<br/><br/>

		<?php if($reponses): ?>
			<div class="table-responsive">
				<table class="center table table-striped table-hover">
					<thead>
						<tr>
							<th></th>
							<th>Intitulé</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						<?php foreach($reponses as $reponse): ?>
							<tr>
								<td>Réponse <?= $reponse['id'];?></td>
								<td><?= $reponse['intitule']; ?></td>
								<td>
									<a href="/qi/supprimerreponse?idReponse=<?= $reponse['id']; ?>&idQi=<?= $_GET['idQi'];?>&idQuestion=<?= $_GET['idQuestion'];?>" onClick="return confirm('Etes vous sur de vouloir supprimer cette réponse ?');" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"> Supprimer</span></a>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		<?php else: ?>
			<p class="center">Il n'y a aucune réponse pour le moment.</p>
		<?php endif; ?>
	</div>
</div>

<!-- MODAL -->
<div class="modal fade" id="ajoutRep" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Ajouter des réponses valides</h4>
			</div>

			<form method="POST" action="/qi/ajoutreponse">
				<div class="modal-body">
					<input type="hidden" name="idQuestion[1]" value="<?= $_GET['idQuestion']; ?>" />
					<input type="hidden" name="idQi[1]" value="<?= $_GET['idQi']; ?>" />
					Réponse 1 : <br />
					<input type="text" class="form-control input_reponse" placeholder="Votre réponse" name="rep[1]"><br/>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-info btn-add">Ajouter plus de réponse</button>
					<button type="submit" class="btn btn-success">Enregistrer</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.btn-add').on('click', function(e){
			nombre = $('.input_reponse').length;
			if (nombre >= 12){
				alert('Vous ne pouvez plus ajouter de réponse.');
			} else {
				$('.modal-body').append('<br /><br />Réponse '+(nombre+1)+
					'<input type="text" class="form-control input_reponse" placeholder="Votre réponse" name="rep['+(nombre+1)+']" /><br/>'
				);
			}
		});
	});
</script>

<?php endif; ?>
