<?php
//on récupère l'url pour déterminer le lien actif
$act = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$ctr = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
//permet de récupérer le module
//$mdl = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$this->placeholder('menu')->captureStart(); 
?>

<div class="sidebar_navigation gradient center">
	<ul>
		<li <? if($ctr == "index" && $act == "index"): ?> <?php endif; ?>>
			<a href="<?= $this->baseUrl('index/index'); ?>">Test</a>
		</li>
	</ul>
</div>

<?php $this->placeholder('menu')->captureEnd();
 
