<?php
//on récupère l'url pour déterminer le lien actif
$act = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$ctr = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
//permet de récupérer le module
//$mdl = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$this->placeholder('menu')->captureStart(); 
?>


<div class="sidebar_navigation gradient center">
	<div class="panel-default">
		<div class="panel-body">
			<ul class="nav nav-pills nav-stacked">
				<?php if ($act == 'index' && $ctr == 'index'): ?>
					<li class="active">
				<?php else: ?>
					<li>
				<?php endif; ?>
					<a href="<?= $this->baseUrl('index/index'); ?>">Accueil</a></li>

				<?php if ($act == 'index' && $ctr == 'user'): ?>
					<li class="active">
				<?php else: ?>
					<li>
				<?php endif; ?>
					<a href="<?= $this->baseUrl('/user/index'); ?>">Gestion des utilisateurs</a></li>

				<?php if ($act == 'index' && $ctr == 'dcp'): ?>
					<li class="active">
				<?php else: ?>
					<li>
				<?php endif; ?>
					<a href="<?= $this->baseUrl('/dcp/index'); ?>">Gestion des DCP</a></li>

				<?php if ($act == 'index' && $ctr == 'qi'): ?>
					<li class="active">
				<?php else: ?>
					<li>
				<?php endif; ?>
					<a href="<?= $this->baseUrl('/qi/index'); ?>">Gestion des QI</a></li>
					
				<?php if ($act == 'index' && $ctr == 'categorie'): ?>
					<li class="active">
				<?php else: ?>
					<li>
				<?php endif; ?>
					<a href="<?= $this->baseUrl('/categorie/index'); ?>">Gestion des catégories</a></li>

				<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
				
			</ul>
		</div>
	</div>
</div>

<?php $this->placeholder('menu')->captureEnd();
