<?php
	$reponses = $this->responsedcp;
	$question = $this->question; 
?>

<div class="row content-heading title">
	<div class="col-xs-11 col-xs-offset-1">
		<h2>Liste des réponses :</h2>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<button class="center btn btn-primary btn-lg" data-toggle="modal" data-target="#ajoutRep">
			Ajouter des réponses
		</button>

		<br/><br/>

		<?php if($reponses): ?>
			<div class="table-responsive">
				<table class="center table table-striped table-hover">
					<thead>
						<tr>
							<th>Intitulé</th>
							<th>Nombre de point</th>
							<th>Effet sur point</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						<?php foreach($reponses as $reponse): ?>
							<tr>
								<td><?= $reponse->intitule; ?></td>
								<td><?= $reponse->nbPoint; ?></td>
								<td><?= $reponse->effetSurPoint; ?></td>
								<td>
									<a href="/dcp/suppReponse/<?= $reponse->id; ?>" onClick="return confirm('Etes vous sur de vouloir supprimer cette réponse ?');" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"> Supprimer</span></a>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		<?php else: ?>
			<p class="center">Il n'y a aucune réponse pour le moment.</p>
		<?php endif; ?>
	</div>
</div>

<!-- MODAL -->
<div class="modal fade" id="ajoutRep" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Ajouter des réponses</h4>
			</div>

			<form method="POST" action="/dcp/ajoutreponse">
				<div class="modal-body">
					<input type="hidden" value="<?= $question['id']; ?>" />
					<input type="text" class="form-control input_reponse" placeholder="Votre réponse" name="rep[1]"><br/>
					<label>Valeur en point(s) :</label>
			   		<select name="point[1]" class="form-control">
			   			<?php for ($i = 1; $i <= 20; $i++): ?>
					   		<option value="<?= $i; ?>"><?= $i; ?></option>
					   	<?php endfor; ?>
			   		</select><br />

			   		<select name="action[1]" class="form-control">
			   			<option value="ajouter">Ajouter</option>
			   			<option value="retirer">Retirer</option>
			   			<option value="neutre">Neutre</option>
			   		</select>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-info btn-add">Ajouter plus de réponse</button>
					<button type="submit" class="btn btn-success">Enregistrer</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.btn-add').on('click', function(e){
			nombre = $('.input_reponse').length;
			if (nombre >= 12){
				alert('Vous ne pouvez plus ajouter de réponse.');
			} else {
				$('.modal-body').append('<input type="text" class="form-control input_reponse" placeholder="Votre réponse" name="rep['+(nombre+1)+']" /><br/>'+
					'<label>Valeur en point(s) :</label>'+
			   		'<select name="point['+(nombre+1)+']" class="form-control">'+
			   			'<option value="1">1</option>'+
			   			'<option value="2">2</option>'+
			   			'<option value="3">3</option>'+
			   			'<option value="4">4</option>'+
			   			'<option value="5">5</option>'+
			   			'<option value="6">6</option>'+
			   			'<option value="7">7</option>'+
			   			'<option value="8">8</option>'+
			   			'<option value="9">9</option>'+
			   			'<option value="10">10</option>'+
						'<option value="11">11</option>'+
			   			'<option value="12">12</option>'+
			   			'<option value="13">13</option>'+
			   			'<option value="14">14</option>'+
			   			'<option value="15">15</option>'+
			   			'<option value="16">16</option>'+
			   			'<option value="17">17</option>'+
			   			'<option value="18">18</option>'+
			   			'<option value="19">19</option>'+
			   			'<option value="20">20</option>'+
			   		'</select><br />'+

			   		'<select name="action['+(nombre+1)+']" class="form-control">'+
			   			'<option value="ajouter">Ajouter</option>'+
			   			'<option value="retirer">Retirer</option>'+
			   			'<option value="neutre">Neutre</option>'+
			   		'</select>'
				);
			}
		});
	});
</script>
