<?= $this->doctype(); ?>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Hackathon Project</title>
		<link href="<?= $this->baseUrl('/css/style.css')?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/css/bootstrap.min.css')?>" media="screen" rel="stylesheet" type="text/css" />
	</head>

	<body>
		<div id="main-wrapper">
		<header>
			<nav class="wrapper-header">
				<div class="container-fluid">
					<div class="row-fluid">
						<?php $auth = Zend_Auth::getInstance();?>
						<?php if ($auth->hasIdentity()): ?>
							<a href="<?= $this->baseUrl('auth/logout')?>" rel="tooltip" class="btn tips icon_logout" data-original-title="Logout"><i class="icon-off"></i> Se déconnecter</a>	
						<?php else: ?>
							<a href="#" rel="tooltip" class="btn btn-primary btn-connect" data-original-title="Login">Connexion</a>
						<?php endif; ?>

						
					</div>
				</div>
			</nav>
		</header>
		</div>
			<div class="container-fluid contenu">
				<div class="row-fluid lecontenu">
					<div class="span12">
						<div class="wrapper">
							<?php if ($auth->hasIdentity()): ?>
								<?= $this->placeholder('menu'); ?>
							<?php endif ; ?>
							<?= $this->layout()->content; ?>
						</div>
					</div>
		    	</div>
		    </div>
			<footer>
				FOOTER
				Site par Matthieu Derache
				2014
			</footer>
			<script type="text/javascript" src="<?= $this->baseUrl('/js/jquery.min.js');?>"></script>
			<script type="text/javascript" src="<?= $this->baseUrl('/js/bootstrap.min.js');?>"></script>
		</section>

		<!-- Modal -->
		<div class="modal fade" id="myModal">
  			<div class="modal-dialog">
   				<div class="modal-content modal_content">
      				<div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        				<h4 class="modal-title">Authentification obligatoire :</h4>
     				</div>
      				<div class="modal-body">
        				<div class="offset4 span3 center" style="margin-top:15px">
							
							<div class="login">
								<form class="form-horizontal" method="POST" action="<?= $this->baseUrl('/auth/login')?>" role="form">
									<div class="form-group">
										<label for="login" class="col-sm-2 control-label">Email</label>
										<div class="col-sm-10">
											<input name="login" class="form-control input_login" type="text" placeholder="Email"/><br/>
										</div>
									</div>
									<div class="form-group">
										<label for="motDePasse" class="col-sm-2 control-label">Mot de passe</label>
										<div class="col-sm-10">
											<input name="motDePasse" class="form-control input_login" type="password" placeholder="Mot de Passe"/><br/>
										</div>
									</div>
									<div class="form-group">
										<div class="col-sm-offset-2 col-sm-10">
											<input name="connexion" class="btn btn-primary btn-lg" type="submit" id="btn-login"/>
										</div>
									</div>
								</form>

								<?php if(isset($this->erreur)):?>
								<div class="alert">
									<?= $this->erreur; ?>
								</div>
								<?php endif;?>
						 	</div>
						</div>
      				</div>
      				<div class="modal-footer">
        				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      				</div>
    			</div><!-- /.modal-content -->
  			</div><!-- /.modal-dialog -->
		</div><!-- /.modal -->

	</body>
</html>

<script type="text/javascript">
	$(document).ready(function(){
		$('.btn-connect').on('click', function(e){
			$('#btn-login').text('Connexion');
			$('.input_login').css('width', '450px');
			$('#myModal').modal();
		})
	});
</script>
