<?= $this->doctype(); ?>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Hackathon Project</title>
		<link href="<?= $this->baseUrl('/css/style.css')?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/css/bootstrap.min.css')?>" media="screen" rel="stylesheet" type="text/css" />
	</head>

	<body>
		<div id="main-wrapper">
		<header>
			<nav class="wrapper-header">
				<div class="container-fluid">
					<div class="row-fluid">
						<?php $auth = Zend_Auth::getInstance();?>
						<?php if ($auth->hasIdentity()): ?>
							<a href="<?= $this->baseUrl('auth/logout')?>" rel="tooltip" class="btn tips icon_logout" data-original-title="Logout"><i class="icon-off"></i> Se déconnecter</a>	
						<?php else: ?>
							<a href="#" rel="tooltip" class="btn btn-primary btn-connect" data-original-title="Login">Connexion</a>
						<?php endif; ?>

						
					</div>
				</div>
			</nav>
		</header>
		</div>
			<div class="container-fluid contenu">
				<div class="row-fluid lecontenu">
					<div class="span12">
						<div class="wrapper">
							<?php if ($auth->hasIdentity()): ?>
								<?= $this->placeholder('menu'); ?>
							<?php endif ; ?>
							<?= $this->layout()->content; ?>
						</div>
					</div>
		    	</div>
		    </div>
			<footer>
				FOOTER
				Site par Matthieu Derache
				2014
			</footer>
			<script type="text/javascript" src="<?= $this->baseUrl('/js/jquery.min.js');?>"></script>
			<script type="text/javascript" src="<?= $this->baseUrl('/js/bootstrap.min.js');?>"></script>
		</section>

		<!-- Modal -->
		<div class="modal fade bs-example-modal-lg" id="myModal" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  			<div class="modal-dialog modal-lg">
   				<div class="modal-content">
      				<div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        				<h4 class="modal-title">Authentification :</h4>
     				</div>
      				<div class="modal-body">
        				<div class="offset4 span3 center" style="margin-top:15px">
	        				<div class="row">
								<div class="col-md-6">
									<div class="login">
										<h3 class="titre_connect">Connexion : </h3>
										<form class="form-horizontal" method="POST" action="<?= $this->baseUrl('/auth/login')?>" role="form">
											<div class="form-group">
												<div class="col-sm-10">
													<input name="login" class="form-control input_login" type="text" placeholder="Mail : exemple@mail.com"/><br/>
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-10">
													<input name="motDePasse" class="form-control input_login" type="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;"/><br/>
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<input name="connexion" class="btn btn-primary btn-lg" type="submit" id="btn-login"/>
												</div>
											</div>
										</form>

										<?php if(isset($this->erreur)):?>
										<div class="alert">
											<?= $this->erreur; ?>
										</div>
										<?php endif;?>
								 	</div>
							 	</div>

							 	<div class="col-md-6">
							 		<div class="inscription">
							 			<h3 class="titre_insc">Inscription :</h3>
							 			<form class="form-horizontal" method="POST" action="<?= $this->baseUrl('/auth/inscription')?>" role="form">
							 				<div class="form-group">
							 					<label for="pseudo" class="col-sm-2 label_inscrip">Pseudo</label>
							 					<div class="col-sm-10">
							 						<input type="text" name="pseudo" class="form-control" placeholder="Toto" />
							 					</div>
							 				</div>

							 				<div class="form-group">
							 					<label for="mail" class="col-sm-2 label_inscrip">Mail</label>
							 					<div class="col-sm-10">
							 						<input type="email" name="mail" class="form-control" placeholder="exemple@mail.com" />
							 					</div>
							 				</div>

							 				<div class="form-group">
							 					<label for="password" class="col-sm-2 label_inscrip">Mot de passe</label>
							 					<div class="col-sm-10">
							 						<input type="password" name="password" class="form-control" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
							 					</div>
							 				</div>

							 				<div class="form-group">
							 					<label for="name" class="col-sm-2 label_inscrip">Nom</label>
							 					<div class="col-sm-10">
							 						<input type="text" name="name" class="form-control" placeholder="Dupont" />
							 					</div>
							 				</div>

							 				<div class="form-group">
							 					<label for="surname" class="col-sm-2 label_inscrip">Prénom</label>
							 					<div class="col-sm-10">
							 						<input type="text" name="surname" class="form-control" placeholder="Martin" />
							 					</div>
							 				</div>

							 				<div class="form-group">
							 					<label for="year" class="col-sm-2 label_inscrip">Année d'étude</label>
							 					<div class="col-sm-10">
							 						<input type="text" name="year" class="form-control" placeholder="5ème année" />
							 					</div>
							 				</div>

							 				<div class="form-group">
							 					<label for="facult" class="col-sm-2 label_inscrip">Faculté</label>
							 					<div class="col-sm-10">
							 						<input type="text" name="facult" class="form-control input_inscript" placeholder="Université de Saint-Quentin" />
							 					</div>
							 				</div>

							 				<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<input name="inscription" class="btn btn-primary btn-lg btn-insc" type="submit" id="btn-inscription"/>
												</div>
											</div>
							 			</form>
							 		</div>
							 	</div>
							</div>
						</div>
      				</div>
    			</div><!-- /.modal-content -->
  			</div><!-- /.modal-dialog -->
		</div><!-- /.modal -->

	</body>
</html>

<script type="text/javascript">
	$(document).ready(function(){
		$('.btn-connect').on('click', function(e){
			$('#btn-login').text('Connexion');
			$('.input_login').css('width', '280px');
			$('#myModal').modal();
		})
	});
</script>