<?= $this->doctype(); ?>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Hackathon Project</title>
		<link href="<?= $this->baseUrl('/css/style.css')?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/css/bootstrap.min.css')?>" media="screen" rel="stylesheet" type="text/css" />
	</head>

	<body>
		<header>
			<nav class="wrapper-header">
				<div class="row">
					<div class="col-md-2 col-md-offset-10">
						<?php $auth = Zend_Auth::getInstance();?>
						<?php if ($auth->hasIdentity()): ?>
							<a href="<?= $this->baseUrl('auth/logout')?>" rel="tooltip" class="btn btn-primary tips icon_logout btn-connect" data-original-title="Logout"><i class="icon-off"></i>Se déconnecter</a>	
						<?php else: ?>
							<a href="#" rel="tooltip" class="btn btn-primary btn-connect" data-original-title="Login" data-toggle="modal" data-target="#modal_connexion">Connexion</a>
						<?php endif; ?>					
					</div>
				</div>
			</nav>
		</header>
		<div class="container-fluid">
			<div class="row body-container">
				<div class="menu_gauche col-md-2 menu">
					<div class="min500">
						<?php if ($auth->hasIdentity()): ?>
							<?= $this->placeholder('menu'); ?>
						<?php endif ; ?>
					</div>
				</div>

				<div class="col-md-10">
					<?= $this->layout()->content; ?>
				</div>
	    	</div>
	    </div>
		<footer>
			<div class="row-fluid clearfix">
				<div class="col-md-4 text-center">
					<ul class="list-inline">
						<li><a>Contactez-nous !</a></li>
						<li><a>Signalez un bug !</a></li>
						<li><a>Qui sommes-nous ?</a></li>
					</ul>
				</div>
				<div class="col-md-4 text-center">
					<ul class="list-inline">
						<li><a>C.G.U.</a></li>
						<li><a>F.A.Q.</a></li>
					</ul>
				</div>
				<div class="col-md-4 text-center">
					<ul class="list-inline">
						<li class="social">
							<a href="http://www.facebook.com">
								<i class="fa fa-facebook fa-inverse"></i>
							</a>
						</li>
						<li class="social">
							<a href="http://www.twitter.com">
								<i class="fa fa-twitter fa-inverse"></i>
							</a>
						</li>
						<li class="social">
							<a href="http://www.plus.google.com">
								<i class="fa fa-google-plus fa-inverse"></i>
							</a>
						</li>
						<li class="social">
							<a href="http://www.instagram.com">
								<i class="fa fa-instagram fa-inverse"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</footer>
			<script type="text/javascript" src="<?= $this->baseUrl('/js/jquery.min.js');?>"></script>
			<script type="text/javascript" src="<?= $this->baseUrl('/js/bootstrap.min.js');?>"></script>

		<!-- Modal -->
		<div class="modal fade bs-example-modal-lg" id="modal_connexion" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  			<div class="modal-dialog modal-lg">
   				<div class="modal-content">
      				<div class="modal-header">
        				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        				<h4 class="modal-title">Authentification :</h4>
     				</div>
      				<div class="modal-body">
        				<div class="row">
							<div class="col-md-5">
								<h3 class="text-center">Connexion : </h3>
								<form class="form-horizontal text-center" method="POST" action="<?= $this->baseUrl('/auth/login')?>" role="form">
									<div class="form-group">
					 					<label class="col-sm-3 control-label">Mail</label>
					 					<div class="col-sm-9">
											<input name="mail" class="form-control" type="text" placeholder="Mail : exemple@mail.com"/>
										</div>
									</div>
									<div class="form-group">
					 					<label class="col-sm-3 control-label">Password</label>
					 					<div class="col-sm-9">
											<input name="pwd" class="form-control" type="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;"/>
										</div>
									</div>
									<div class="form-group">
										<input value="Connexion" name="connexion" class="btn btn-primary btn-lg" type="submit" id="btn-login"/>
									</div>
								</form>

								<?php if(isset($this->erreur)):?>
								<div class="alert">
									<?= $this->erreur; ?>
								</div>
								<?php endif;?>
						 	</div>

						 	<div class="col-md-7">
					 			<h3 class="text-center">Inscription :</h3>
					 			<form class="form-horizontal text-center" method="POST" action="<?= $this->baseUrl('/auth/inscription')?>" role="form">
					 				<div class="form-group">
					 					<label for="pseudo" class="col-sm-2 control-label">Pseudo</label>
					 					<div class="col-sm-10">
					 						<input type="text" name="pseudo" class="form-control" placeholder="Votre pseudo" />
					 					</div>
					 				</div>

					 				<div class="form-group">
					 					<label for="mail" class="col-sm-2 control-label">Mail</label>
					 					<div class="col-sm-10">
					 						<input type="email" name="mail" class="form-control" placeholder="exemple@mail.com" />
					 					</div>
					 				</div>

					 				<div class="form-group">
					 					<label for="password" class="col-sm-2 control-label">Mot de passe</label>
					 					<div class="col-sm-10">
					 						<input type="password" name="password" class="form-control" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
					 					</div>
					 				</div>

					 				<div class="form-group">
					 					<label for="name" class="col-sm-2 control-label">Nom</label>
					 					<div class="col-sm-10">
					 						<input type="text" name="name" class="form-control" placeholder="Nom" />
					 					</div>
					 				</div>

					 				<div class="form-group">
					 					<label for="surname" class="col-sm-2 control-label">Prénom</label>
					 					<div class="col-sm-10">
					 						<input type="text" name="surname" class="form-control" placeholder="Prénom" />
					 					</div>
					 				</div>

					 				<div class="form-group">
					 					<label for="year" class="col-sm-2 control-label">Année d'étude</label>
					 					<div class="col-sm-10">
					 						<input type="text" name="year" class="form-control" placeholder="2014" />
					 					</div>
					 				</div>

					 				<div class="form-group">
					 					<label for="facult" class="col-sm-2 control-label">Faculté</label>
					 					<div class="col-sm-10">
					 						<input type="text" name="facult" class="form-control input_inscript" placeholder="Université de Saint-Quentin" />
					 					</div>
					 				</div>

					 				<div class="form-group">
										<input value="S'inscrire" name="inscription" class="btn btn-primary btn-lg" type="submit" id="btn-inscription"/>
									</div>
					 			</form>
						 	</div>
						</div>
      				</div>
    			</div><!-- /.modal-content -->
  			</div><!-- /.modal-dialog -->
		</div><!-- /.modal -->

	</body>
</html>
