<?= $this->doctype(); ?>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Hackathon Project</title>
		<script type="text/javascript" src="<?= $this->baseUrl('/js/jquery.min.js');?>"></script>
		<link href="<?= $this->baseUrl('/css/style.css');?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="<?= $this->baseUrl('/css/normalize.css');?>" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?= $this->baseUrl('js/jwplayer/jwplayer.js')?>"></script>
		<link href="<?= $this->baseUrl('/css/bootstrap.min.css')?>" media="screen" rel="stylesheet" type="text/css" />
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	</head>

	<body>
		<header>
			<nav class="wrapper-header">
				<div class="row">
					<div class="col-md-2 col-md-offset-10">
							<?php $auth = Zend_Auth::getInstance();?>
							<?php if ($auth->hasIdentity()): ?>
								<a href="<?= $this->baseUrl('auth/logout')?>" rel="tooltip" class="btn btn-primary tips icon_logout btn-connect" data-original-title="Logout"><i class="icon-off"></i> Se déconnecter</a>
							<?php endif; ?>
					</div>
				</div>
			</nav>
		</header>
		<div class="container-fluid">
			<div class="row body-container">
				<div class="menu_gauche col-md-2 menu">
					<?php if ($auth->hasIdentity()): ?>
						<?= $this->placeholder('menu'); ?>
					<?php endif ; ?>
				</div>
				<div class="col-md-8">
					<div class="content">
						<?= $this->layout()->content; ?>
					</div>
				</div>
				<div class="menu_droite col-md-2 hidden-xs menu">
					<?php if ($auth->hasIdentity()): ?>
						<?= $this->placeholder('menudroite'); ?>
					<?php endif ; ?>
				</div>
	    	</div>
		</div> 
		<footer>
			<div class="row-fluid clearfix">
				<div class="col-md-4 text-center">
					<ul class="list-inline">
						<li>Contactez-nous</li>
						<li>Signalez un bug</li>
						<li>Qui sommes-nous ?</li>
					</ul>
				</div>
				<div class="col-md-4 text-center">
					<ul class="list-inline">
						<li>Réglement</li>
						<li>Publicité</li>
						<li>Blabla</li>
					</ul>
				</div>
				<div class="col-md-4 text-center">
					<ul class="list-inline">
						<li class="social">
							<a href="http://www.facebook.com">
								<i class="fa fa-facebook fa-inverse"></i>
							</a>
						</li>
						<li class="social">
							<a href="http://www.twitter.com">
								<i class="fa fa-twitter fa-inverse"></i>
							</a>
						</li>
						<li class="social">
							<a href="http://www.plus.google.com">
								<i class="fa fa-google-plus fa-inverse"></i>
							</a>
						</li>
						<li class="social">
							<a href="http://www.instagram.com">
								<i class="fa fa-instagram fa-inverse"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</footer>
		<script type="text/javascript" src="<?= $this->baseUrl('/js/bootstrap.min.js');?>"></script>
	</body>
</html>
